version: '3.8'
services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "95a3FqXFsUDhxRd"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql